### ISSUE TITLE
0-AboutLecture ready ?

### ISSUE THREAD

**Issue by MarieCollin** [pharo-mooc/AdvancedOODesign#25]
https://rmod-files.lille.inria.fr/DesignCoffeeClub/ForLearningLab2/0-AboutLecture.pdf

Cette séquence ne semble pas prête : références à des semaines, planning étudiants et exams université, ...

**Comment by Ducasse** [comment]
voir 0-AboutTheMooc.pillar

**Comment by Ducasse** [comment]
I put it in the server.
