### ISSUE TITLE
About the template

### ISSUE THREAD

**Issue by MarieCollin** [pharo-mooc/AdvancedOODesign#27]
Voici qq remarques après la relecure de l'ensemble des slides déposées sur https://rmod-files.lille.inria.fr/DesignCoffeeClub/ForLearningLab2, et indépendament des questions d'accessibilité:

- Attention à la position du titre du Mooc en limite de slide pour certaines séquences (par exemple https://rmod-files.lille.inria.fr/DesignCoffeeClub/ForLearningLab2/M1-4-Essence-04-Self.pdf) --> est-il possible d'assurer un bord minimal lors de la génération du pdf ?
- souvent, il n'y pas beacoup de place pour intégrer une vue de l'intervenant en bas à droite des slides
  - c'est ok quand on utilise la vue plein écran de la tablette graphique (sans doute le plus souvent)
  - proposition pour intégrer la vue de l'intervenant (avec son nom, sa fonction, son organisme) a minima à chaque séquence :
    -  sur la droite de la slide 1 avec réduisant la taille de l'image du cerveau 
    -  sur la slide "Objectives/ Goals" 
    -  puis sur slide Recap / conclusion
- A-t-on les droits de l'auteur et quel crédit mentionner pour l'image du cerveau ?
- Indiquer le titre complet du cours tel que prévu sur FUN sur la slide de fin : Advanced object oriented design and development with Pharo

**Comment by Ducasse** [comment]
- Le cerveau ne sera pas utilisé. Un designeur doit nous fournir qqchose et sinon on est dans la mouise.
- [DONE] Advanced object oriented design and development with Pharo
- Je vais finir mes tickets et apres je vais bosser sur les slides de mes petits camarades (et ceux que je connais etre faibles car j'etais trop fatigue pour les faire mieux).

**Comment by Ducasse** [comment]
Je vais demander a luc pour le bord du titre.

**Comment by LucFabresse** [comment]
je pense que tous les points ont été traités
