### ISSUE TITLE
M3-2-Essence-07-SelfSendsArePlansForReuse (template methods)

### ISSUE THREAD

**Issue by tkhomenko** [pharo-mooc/AdvancedOODesign#36]
https://github.com/pharo-mooc/AdvancedOODesign/blob/master/__results.luc/M3-2-Essence-07-SelfSendsArePlansForReuse.pdf

- p.4 Let us start to reflect => Let's start thinking (?) 
- p.10 : Applying it to our example
- p. 16 ajouter le crédit image

[16/05/2023 à 11:22]

**Comment by Ducasse** [comment]
Oui.
