### ISSUE TITLE
M3-3-DesignPattern-02-HookAndTemplate (Copy PostCopy)

### ISSUE THREAD

**Issue by tkhomenko** [pharo-mooc/AdvancedOODesign#37]
https://github.com/pharo-mooc/AdvancedOODesign/blob/master/__results.luc/M3-3-DesignPattern-02-HookAndTemplate.pdf

- p.17 : Hooks and Template is (are ?) a very common pattern 

[16/05/2023 à 11:23]

**Comment by LucFabresse** [comment]
done
