### ISSUE TITLE
M05_S3 direction instead of distance!

### ISSUE THREAD

**Issue by Ducasse** [pharo-mooc/AdvancedOODesign#75]
![IMG_2838](https://github.com/pharo-mooc/AdvancedOODesign/assets/432549/8ad2415e-bb0b-4d90-87ae-9b3f6cdc400a)

**Comment by sherazadeD** [comment]
Bonjour Stéphane, j’ai pu effectuer les modifications. Tu peux télécharger la dernière version de la vidéo dans le nouvel export (voir mail du 11/03).
