### ISSUE TITLE
Subtitles correction for @Luc

### ISSUE THREAD

**Issue by sherazadeD** [pharo-mooc/AdvancedOODesign#76]
Bonjour @LucFabresse , pour les vidéos suivantes peux-tu me dire ce que tu dis aux parties inaudibles ?

[M1_S3](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M01_S3.mp4) : 
- 3:46 "If I send a message to this object,
for example, a (**inaudible**) message."
- 4:02 "It will check if the (**inaudible**)
message exists."

[M4_S1](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M04_S1.mp4) :
- 2:57 "And this is just because we (**inaudible**)
the API of nodes with the fact that"

[M9_S2](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M09_S2.mp4) :
- 5:46 "to (**inaudible**) the system each time."

Merci,

Sherazade

**Comment by LucFabresse** [comment]
Bonjour @LucFabresse , pour les vidéos suivantes peux-tu me dire ce que tu dis aux parties inaudibles ?

[M1_S3](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M01_S3.mp4) :

    3:46 "If I send a message to this object,
    for example, **I send the area** message."

    4:02 "It will check if the **area** message exists."

[M4_S1](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M04_S1.mp4) :

    2:57 "And this is just because we  **enrich**
    the API of nodes with the fact that"

[M9_S2](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M09_S2.mp4) :

    5:46 "to **query** the system each time."

French accent ;-)

Luc

Merci,

Sherazade

**Comment by sherazadeD** [comment]
C'est parfait, merci !
