### ISSUE TITLE
Subtitles correction for @pablo

### ISSUE THREAD

**Issue by sherazadeD** [pharo-mooc/AdvancedOODesign#77]
Bonjour @tesonep , pour les vidéos suivantes peux-tu me dire ce que tu dis aux parties inaudibles ?

[M4_S4](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M04_S4.mp4) : 
- 7:44 "So, we have to take care of this
and this is (**inaudible**) that we..."

[M7_S7](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M07_S7_V2.mp4) : 
- 9:53 "a text and a ceiling of that will
be a bold element wrapping another **(test or text?)**"

Merci,

Sherazade

**Comment by tesonep** [comment]
> Bonjour @tesonep , pour les vidéos suivantes peux-tu me dire ce que tu dis aux parties inaudibles ?
> 
> [M4_S4](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M04_S4.mp4) :
> 
> * 7:44 "So, we have to take care of this
>   and this is (**inaudible**) that we..."

7:44 "So, we have to take care of this and this is **a smell** that we..."


> 
> [M7_S7](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M07_S7_V2.mp4) :
> 
> * 9:53 "a text and a ceiling of that will
>   be a bold element wrapping another **(test or text?)**"

* 9:53 "a text and a ceiling of that will  be a bold element wrapping another **text**"

> 
> Merci,
> 
> Sherazade
