### ISSUE TITLE
Subtitle correction for @Stephane

### ISSUE THREAD

**Issue by sherazadeD** [pharo-mooc/AdvancedOODesign#78]
Bonjour @Ducasse , pour la vidéo suivante peux-tu me dire ce que tu dis à la partie inaudible ?

[M7_S5](http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/Videos/M07_S5.mp4) : 
- 14:23 "If I'm (**inaudible**) else, I will return the oldPharo
version."

Merci,

Sherazade

**Comment by Ducasse** [comment]
Salut

en fait je pense que l'on pourrait modifier la bande sonore pour enlever le "mot".
Je n'arrive pas a avoir l'interval exact de la bande que l'on pourrait enlever. mais on peut enlever le son avant le else.14:22 - 14:23 J'ai essaye avec VLC en mode super lent.

En fait on peut enlever le son apres class definition printer.... "if i'm conf" else 
Est ce que vous pouvez enlever if I'm conf?

I think that this is if I'm configured

**Comment by sherazadeD** [comment]
Bonjour Stéphane, j'ai pu supprimer le son "if i'm conf", tu peux télécharger la dernière version de la vidéo dans le nouvel export (voir mail du 11/03). J'espère que ça te convient.
