### ISSUE TITLE
Booklet Chapter 5

### ISSUE THREAD

**Issue by sherazadeD** [pharo-mooc/AdvancedOODesign#88]
**Reçu sur l'adresse mail du Learning Lab (ill-contact@inria.fr)**

"Hi,
I am having a big problem with:
Advanced object oriented design and development with Pharo

I have a problem with Module 1: Companion exercises.

the book http://rmod-pharo-mooc.lille.inria.fr/AdvancedDesignMooc/2024-04-01-CompanionExercise.pdf
page 21 (31 of 170)
assumes knowledge I do not have.

Sorry for being a dumb student, but pharo launcher has several versions available? Which one I am supposed to use?

How on earth am I supposed to use the Pharo interface to perform those basic tasks?

Is there a youtube video that shows how to do it with the recommended Pharo version?"

**Comment by Ducasse** [comment]
This person should 
- follow the first mooc 
- ask on channel help newbie on the discord server.

**Comment by Ducasse** [comment]
And it should explain clearly what he does not understand. For now I will not do anything because there is nothing I can do.

**Comment by sherazadeD** [comment]
Merci Stéphane, on lui a répondu avec ces éléments et voici sa réponse :

 " I looked for help on Smalltalk reddit and played a bit with Squeak which is more beginner friendly. That has helped with my UI problems with Pharo. Maybe the Pharo UI is perfect for a Smalltalk veteran but I found it infuriating.

Despite the Pharo UI problems, I can continue going through the exercises. 

Discord was not very helpful. You appear to be a clerk in the office without the understanding of my problems. You did not understand or try to answer my question. But still, thank you for proving that somebody is there on the other end and that person can escalate my questions further if needed."

**Comment by Ducasse** [comment]
- It is not true that Squeak is more friendly :)
- I do not get why Discord specific channel for helping newbie is bad. Now all these complains are not actionable.
- I would not comment "You appear to be a clerk in the office without the understanding of my problems. 
You did not understand or try to answer my question". To me this person is complaining without giving us any way that we can help. So let us not lose time with this.
